spring:
  application:
    name: migration-service

  # ✅ PostgreSQL (JDBC)
  datasource:
    url: jdbc:postgresql://postgres:5432/currency_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # ✅ Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml    